import { Tokens } from "@origami/tokens.slint";

export component AppTextField inherits Rectangle {
    in-out property <string> text <=> input.text;
    in property <string> placeholder-text;
    in property <bool> enabled: true;
    in property <bool> read-only: false;
    in property <InputType> input-type: InputType.text;
    out property <bool> has-focus: input.has-focus;
    callback accepted();
    callback edited(string);

    height: 32px;
    border-radius: Tokens.corner-radius;
    border-width: input.has-focus ? 1.5px : Tokens.border-width;
    border-color: !root.enabled ? Tokens.border-on-surface : input.has-focus ? Tokens.accent : (touch.has-hover ? Tokens.border-hover-on-surface : Tokens.border-on-surface);
    background: !root.enabled ? Tokens.background : Tokens.surface;

    animate border-color {
        duration: Tokens.anim-very-short * 1ms;
        easing: ease-out;
    }
    animate border-width {
        duration: Tokens.anim-very-short * 1ms;
        easing: ease-out;
    }
    animate background { duration: Tokens.anim-very-short * 1ms; }

    HorizontalLayout {
        padding-left: Tokens.spacing-medium;
        padding-right: Tokens.spacing-medium;

        input := TextInput {
            enabled: root.enabled;
            read-only: root.read-only;
            input-type: root.input-type;
            color: root.enabled ? Tokens.text-primary : Tokens.text-disabled-on-surface;
            font-size: Tokens.font-size-normal;
            vertical-alignment: center;
            horizontal-alignment: left;
            accepted => { root.accepted(); }
            edited => { root.edited(self.text); }
        }
    }

    if root.text == "" && root.placeholder-text != "" && !input.has-focus: Text {
        x: Tokens.spacing-medium;
        text: root.placeholder-text;
        color: Tokens.text-disabled-on-surface;
        font-size: Tokens.font-size-normal;
        vertical-alignment: center;
    }

    touch := TouchArea {
        enabled: root.enabled;
        mouse-cursor: MouseCursor.text;
        clicked => { input.focus(); }
    }
}
