[workspace]
resolver = "3"

members = [
  "origami",
  "origami-gallary"
]

default-members = ["origami"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.6", features = ["derive"] }
cxx = "1"
cxx-qt = "0.9"
cxx-qt-lib = "0.9"
cxx-qt-build = "0.9"
directories = "6.0"
serde = { version = "1.0", features = ["derive"] }
time = "0.3"
toml = "0.8"
