[workspace]
resolver = "3"

members = [
  "origami",
  "origami-build",
  "origami-gallery",
  "origami-kit/config",
  "origami-kit/panes",
  "origami-kit/theme",
  "origami-kit/viewport",
]

default-members = ["origami-gallery"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
origami = { path = "origami" }
origami-build = { path = "origami-build" }
origami-config = { path = "origami-kit/config" }
origami-panes = { path = "origami-kit/panes" }
origami-theme = { path = "origami-kit/theme" }
origami-viewport = { path = "origami-kit/viewport" }

#= Crates.io
anyhow = "1"
ash = "0.38"
clap = { version = "4.6", features = ["derive"] }
directories = "6.0"
naga = { version = "30", features = ["spv-out", "wgsl-in"] }
notify = "8.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
slint = { version = "1.18", default-features = false, features = [
  "backend-winit",
  "compat-1-2",
  "renderer-skia",
  "unstable-wgpu-30",
] }
slint-build = "1.18"
sysinfo = "0.39"
time = "0.3"
toml = "0.8"
tracy-client = { version = "0.18", default-features = false }
trash = "5.2.6"
wgpu = { version = "30", default-features = false, features = ["wgsl"] }
wgpu-hal = { version = "30", features = ["vulkan"] }

[profile.dev.package."*"]
opt-level = 3
