[workspace]
resolver = "3"

members = [
  # "origami",
  # "origami-gallery",
  "origami-gallery-slint",
  "origami-kit/config",
  "origami-kit/panes",
  # "origami-kit/views/settings",
  "origami-kit/vulkan-bridge",
  "origami-slint",
  "origami-slint-build",

  #[ Ayame Core & Slint ]
  "ayame/colors",
  "ayame/config",
  "ayame/icons",
  "ayame/slint",
  "ayame/slint-build",
]

# default-members = ["origami"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# origami = { path = "origami" }
origami-config = { path = "origami-kit/config" }
origami-panes = { path = "origami-kit/panes" }
# origami-view-settings = { path = "origami-kit/views/settings" }
origami-vulkan-bridge = { path = "origami-kit/vulkan-bridge" }
origami-slint = { path = "origami-slint" }
origami-slint-build = { path = "origami-slint-build" }
ayame-colors = { path = "ayame/colors" }
ayame-config = { path = "ayame/config" }
ayame-icons = { path = "ayame/icons" }
ayame-slint = { path = "ayame/slint" }
ayame-slint-build = { path = "ayame/slint-build" }

#[ Crates.io ]
anyhow = "1"
clap = { version = "4.6", features = ["derive"] }
cxx = "1"
cxx-qt = "0.9"
cxx-qt-lib = "0.9"
cxx-qt-build = "0.9"
qt-build-utils = "0.9.1"
directories = "6.0"
notify = "8.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
slint = { version = "1.17", features = ["backend-winit", "renderer-skia-vulkan"] }
slint-build = "1.17"
sysinfo = "0.39"
tracy-client = { version = "0.18", default-features = false }
time = "0.3"
trash = "5.2.6"
toml = "0.8"
