import { Tokens } from "@origiri/tokens.slint";
import { Icon, TablerIcons } from "@origiri-icons/icons.slint";

export component CheckBox inherits Rectangle {
    in property <string> text;
    in-out property <bool> checked: false;
    in property <bool> enabled: true;
    callback toggled(bool);

    height: max(22px, layout.preferred-height);
    width: layout.preferred-width;

    layout := HorizontalLayout {
        spacing: Tokens.spacing-medium;
        alignment: start;

        box := Rectangle {
            width: 18px;
            height: 18px;
            y: (parent.height - self.height) / 2;
            border-radius: Tokens.corner-radius;
            border-width: Tokens.border-width;
            border-color: !root.enabled ? Tokens.border-on-raised : root.checked ? Tokens.accent : (touch.has-hover ? Tokens.accent : Tokens.border-on-raised);
            background: !root.enabled ? (root.checked ? Tokens.border-on-raised : Tokens.surface-raised) : root.checked ? (touch.pressed ? Tokens.accent-pressed : touch.has-hover ? Tokens.accent-hover : Tokens.accent) : (touch.has-hover ? Tokens.hover-on-raised : Tokens.surface-raised);

            animate background {
                duration: Tokens.anim-very-short * 1ms;
                easing: ease-out;
            }
            animate border-color {
                duration: Tokens.anim-very-short * 1ms;
                easing: ease-out;
            }

            if root.checked: Icon {
                source: TablerIcons.check;
                color: root.enabled ? Tokens.text-on-accent : Tokens.text-primary;
                width: touch.pressed ? 10px : 13px;
                height: touch.pressed ? 10px : 13px;
                x: (parent.width - self.width) / 2;
                y: (parent.height - self.height) / 2;
                animate width {
                    duration: Tokens.anim-very-short * 1ms;
                    easing: cubic-bezier(0.2, 0.9, 0.3, 1.2);
                }
                animate height {
                    duration: Tokens.anim-very-short * 1ms;
                    easing: cubic-bezier(0.2, 0.9, 0.3, 1.2);
                }
            }
        }

        if root.text != "": Text {
            text: root.text;
            color: Tokens.text-primary;
            font-size: Tokens.font-size-normal;
            vertical-alignment: center;
        }
    }

    touch := TouchArea {
        enabled: root.enabled;
        mouse-cursor: root.enabled ? pointer : default;
        clicked => {
            root.checked = !root.checked;
            root.toggled(root.checked);
        }
    }
}
