[package]
name = "origami-gallery-slint"
version.workspace = true
edition.workspace = true

[[bin]]
name = "origami-gallery-slint"
path = "src/main.rs"

[dependencies]
slint = { workspace = true }
origami-theme = { workspace = true }
origami-slint = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
origami-slint-build = { workspace = true }
