[package]
name = "origami"
links = "origami"
version.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
ayame = { workspace = true }
origami-config = { workspace = true }

# === Crates.io ===
cxx = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
notify = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }

[build-dependencies]
cxx-qt-build = { workspace = true }
