import { Palette } from "std-widgets.slint";
import { Metrics } from "@origami-mobile/tokens.slint";
import { Icon, TablerIcons } from "@origami-icons/icons.slint";

export component Fab inherits Rectangle {
    in property <bool> enabled: true;
    callback clicked();

    width: Metrics.fab;
    height: Metrics.fab;
    border-radius: self.width / 2;
    background: Palette.accent-background;
    drop-shadow-blur: 8px;
    drop-shadow-offset-y: 2px;
    drop-shadow-color: #00000055;

    Icon {
        source: TablerIcons.plus;
        color: Palette.accent-foreground;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }

    TouchArea {
        clicked => { root.clicked(); }
    }
}
